name: backend test

on: 
  push:
    branches:
      - backend_test 
      - main
      - GitHub_action
  pull_request:
    branches:  
      - main 

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        mongodb-version: ['5.0']

    steps:
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - uses: actions/checkout@v3
      - name: Start test
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
        working-directory: backend
      - run: npm run build --if-present
        working-directory: backend
      - run: npm test
        working-directory: backend